@echo off
if "%cd:~0,1%"=="C" goto end
echo maked by hbendali 2017/06/27 b18 usb build 2
echo https://github.com/hbendalibraham/bucleaner
echo -----------------------------------------------

echo - Task killer
taskkill /im wscript.exe /f /t >nul 2>&1
taskkill /im showmyhey.exe /f /t >nul 2>&1
taskkill /im microsoft.exe /f /t >nul 2>&1
taskkill /im msiexec.exe /f /t >nul 2>&1
taskkill /im mspaint.exe /f /t >nul 2>&1
taskkill /im mscalc.exe /f /t >nul 2>&1
taskkill /im calc.exe /f /t >nul 2>&1
taskkill /im autoit3.exe /f /t >nul 2>&1
taskkill /im jusched.exe /f /t >nul 2>&1
taskkill /im chrome.exe /f /t >nul 2>&1
taskkill /im AdobeARM.exe /f /t >nul 2>&1
taskkill /im powershell.exe /f /t >nul 2>&1
taskkill /im sidebar.exe /f /t >nul 2>&1
taskkill /im notepad.exe /f /t >nul 2>&1
taskkill /im armsvc.exe /f /t >nul 2>&1
taskkill /im vprot.exe /f /t >nul 2>&1
taskkill /im webshots.scr /f /t >nul 2>&1
taskkill /im PCCompanion.exe /f /t >nul 2>&1
taskkill /im msnmsgr.exe /f /t >nul 2>&1
taskkill /im msmsgs.exe /f /t >nul 2>&1
taskkill /im WgaTray.exe /f /t >nul 2>&1
taskkill /im jqs.exe /f /t >nul 2>&1
taskkill /im FABS.exe /f /t >nul 2>&1
taskkill /im FABS.exe /f /t >nul 2>&1
taskkill /im ONENOTEM.EXE /f /t >nul 2>&1

echo - UnHide Folder
attrib -h -r -s -a *.* >nul 2>&1
for /R %%a in (.) do @attrib -h -r -s -a "%%a" >nul 2>&1

echo - Delete File

set f=    "*.lnk" "*.ico" "~$*.*" "*.tmp" "*.vbs"
set f=%f% ".exe"
set f=%f% "ÿ.exe"
set f=%f% "abk.bat"
set f=%f% "AdobeR.exe"
set f=%f% "algsrv.exe"
set f=%f% "algsrvs.exe"
set f=%f% "ansil.exe"
set f=%f% "ants3set.exe"
set f=%f% "Au_.exe"
set f=%f% "auto.exe"
set f=%f% "autorun.*"
set f=%f% "avpo.exe"
set f=%f% "BadGirl.exe"
set f=%f% "bar311.exe"
set f=%f% "bjdenp.exe"
set f=%f% "blanca de nieve.exe"
set f=%f% "boot.exe"
set f=%f% "BOOTEX.log"
set f=%f% "Boss Game.exe"
set f=%f% "Boy and Girl.exe"
set f=%f% "bqk.bat"
set f=%f% "bymom.cmd"
set f=%f% "c.com"
set f=%f% "c9.com"
set f=%f% "c9hehpa.bat"
set f=%f% "calculator.exe"
set f=%f% "ccsvchst.exe"
set f=%f% "cfg.exe"
set f=%f% "ch.exe"
set f=%f% "Cheat.exe"
set f=%f% "Choose Games.exe"
set f=%f% "Click Me.exe"
set f=%f% "co.com"
set f=%f% "config_.com"
set f=%f% "conmgr.exe"
set f=%f% "copetttt.com"
set f=%f% "copy.exe"
set f=%f% "csrcs.exe"
set f=%f% "ctfmon.exe"
set f=%f% "cubp.bat"
set f=%f% "d.cmd"
set f=%f% "desktop.ini"
set f=%f% "dh66ln.cmd"
set f=%f% "diox3j.com"
set f=%f% "dir32.exe"
set f=%f% "displa~1.exe"
set f=%f% "DisplayMonitor.exe"
set f=%f% "displa~1.exe"
set f=%f% "dmham.cmd"
set f=%f% "drv32.exe"
set f=%f% "dwarf4you.exe"
set f=%f% "dwdiag.exe"
set f=%f% "ek.com"
set f=%f% "ekf6dbg0.com"
set f=%f% "ekugb3.bat"
set f=%f% "enano porno.exe"
set f=%f% "ev60a2.cmd"
set f=%f% "explorer.doc"
set f=%f% "f.bat"
set f=%f% "f.exe"
set f=%f% "f2ir.com"
set f=%f% "fbxrqtwn.exe"
set f=%f% "fe.bat"
set f=%f% "festas.exe"
set f=%f% "FILE*.CHK"
set f=%f% "FileKan.exe"
set f=%f% "flashy.exe"
set f=%f% "forever.exe"
set f=%f% "found.000"
set f=%f% "fucker.com"
set f=%f% "fucker.exe"
set f=%f% "fun.xls.exe"
set f=%f% "funnyu~1.exe"
set f=%f% "flashy.exe"
set f=%f% "gasretyw0.dll"
set f=%f% "gasretyw1.dll"
set f=%f% "gasretyw2.dll"
set f=%f% "gasretyw3.dll"
set f=%f% "gi2ky.exe"
set f=%f% "glxyr.cmd"
set f=%f% "GoodGame.exe"
set f=%f% "gphone.exe"
set f=%f% "gsxlexd.cmd"
set f=%f% "gumkrhf.bat"
set f=%f% "h.cmd"
set f=%f% "h1ahxi.bat"
set f=%f% "h3hi1k3.exe"
set f=%f% "h8txw.exe"
set f=%f% "ha.cmd"
set f=%f% "Happy New Year.exe"
set f=%f% "Happy.exe"
set f=%f% "happy99.exe"
set f=%f% "Heap41a"
set f=%f% "Heap41a.exe"
set f=%f% "hidec.exe"
set f=%f% "hidecexe"
set f=%f% "hinhem.scr"
set f=%f% "h8txw.exe"
set f=%f% "host.exe"
set f=%f% "hovrflst.bat"
set f=%f% "Heap41a"
set f=%f% "i.bat"
set f=%f% "ie.exe"
set f=%f% "iloveher.exe"
set f=%f% "imt8.cmd"
set f=%f% "imvo.exe"
set f=%f% "inetsrv.exe"
set f=%f% "IndexerVolumeGuid"
set f=%f% "infmgr.exe"
set f=%f% "infrom.dat"
set f=%f% "infvkcsy.bat"
set f=%f% "ipy.cmd"
set f=%f% "iq0ecwcj.cmd"
set f=%f% "isi32.exe"
set f=%f% "isis32.exe"
set f=%f% "ixmuj.exe"
set f=%f% "j.cmd"
set f=%f% "j6154022.exe"
set f=%f% "jfvkcsy.bat"
set f=%f% "just.exe"
set f=%f% "jwgkvsq.vmx"
set f=%f% "k08aww.bat"
set f=%f% "k0wc.cmd"
set f=%f% "ka1nk.bat"
set f=%f% "kagen.exe"
set f=%f% "kamsoft.exe"
set f=%f% "kavo.exe"
set f=%f% "kavo0.dll"
set f=%f% "kavo1.dll"
set f=%f% "killer.exe"
set f=%f% "knight.bat"
set f=%f% "knight.exe"
set f=%f% "killer.exe"
set f=%f% "knight.exe"
set f=%f% "kowc.cmd"
set f=%f% "kqsr.exe"
set f=%f% "krag.exe"
set f=%f% "Krnl132.exe"
set f=%f% "kvxo.exe"
set f=%f% "l9dwu8.bat"
set f=%f% "ld.exe"
set f=%f% "ldjs.txt"
set f=%f% "ldlist.txt"
set f=%f% "ldup.exe"
set f=%f% "lgcadwx.bat"
set f=%f% "life_stages.txt.shs"
set f=%f% "love-letter-for-you.htm"
set f=%f% "lsasse~1.exe"
set f=%f% "lvpwmgh.exe"
set f=%f% "Macromedia_Setup.exe"
set f=%f% "Make More Money.exe"
set f=%f% "McRegWizz.exe"
set f=%f% "mdm.exe"
set f=%f% "Merry.exe"
set f=%f% "MicroAV.cpl"
set f=%f% "Microsoft.exe"
set f=%f% "MicrosoftPowerPoint.exe"
set f=%f% "mje12tni.exe"
set f=%f% "mka.bat"
set f=%f% "mmc.exe"
set f=%f% "movie.avi.pif"
set f=%f% "MP3.exe"
set f=%f% "ms.config`.exe"
set f=%f% "MS-DOS.EXE"
set f=%f% "MSDOS.EXE"
set f=%f% "MS-DOS.com"
set f=%f% "MSDOS.com"
set f=%f% "msfun80.exe"
set f=%f% "msime82.exe"
set f=%f% "mspowerpoint.exe"
set f=%f% "msrm.exe"
set f=%f% "msvcr71.dll"
set f=%f% "Music.exe"
set f=%f% "mydocu~1.exe"
set f=%f% "My Game.exe"
set f=%f% "My Letter.exe" 
set f=%f% "My Music.exe"
set f=%f% "My Picture.exe" 
set f=%f% "My Resume.exe" 
set f=%f% "mydocu~1.exe "
set f=%f% "n6j.com "
set f=%f% "Nail.exe "
set f=%f% "New Folder.exe "
set f=%f% "New_Folder.exe "
set f=%f% "NewFolder.exe "
set f=%f% "nideiect.com "
set f=%f% "nideiect.com "
set f=%f% "nircmd.com "
set f=%f% "noskrnl.exe "
set f=%f% "Nouveau.exe"
set f=%f% "np.exe"
set f=%f% "nqhywz.exe"
set f=%f% "nsv.bat"
set f=%f% "ntconf~1.exe"
set f=%f% "ntconf~2.exe"
set f=%f% "ntde1ect.bat"
set f=%f% "ntde1ect.com"
set f=%f% "ntdelect.bat"
set f=%f% "ntdelect.com"
set f=%f% "ntkros.dll"
set f=%f% "ntsys.exe"
set f=%f% "NTSys.exe"
set f=%f% "ntde1ect.com"
set f=%f% "nideiect.com"
set f=%f% "ntdelect.com"
set f=%f% "New Folde*.exe"
set f=%f% "noskrnl.exe"
set f=%f% "o4154027.exe"
set f=%f% "o9o2u.bat"
set f=%f% "obc3wrq3.bat"
set f=%f% "ohniko.pif"
set f=%f% "oka3yrf.bat"
set f=%f% "omue.exe"
set f=%f% "oso.exe"
set f=%f% "oufddh.exe"
set f=%f% "otup.cmd"
set f=%f% "otup.pif"
set f=%f% "pagefile.exe"
set f=%f% "pagefile.pif"
set f=%f% "passwo~1.exe"
set f=%f% "passwo~1.exe"
set f=%f% "password_viewer.exe"
set f=%f% "pc-off.bat"
set f=%f% "pendrive.exe"
set f=%f% "PenHouse.exe"
set f=%f% "photos~1.exe"
set f=%f% "photos.exe"
set f=%f% "Porn.exe"
set f=%f% "portsv.exe"
set f=%f% "planet.exe"
set f=%f% "PlayBoy.exe"
set f=%f% "portsv.exe"
set f=%f% "pretty park.exe"
set f=%f% "prettypark.exe"
set f=%f% "Question.exe"
set f=%f% "Ravmon.exe"
set f=%f% "RavMonE.bat"
set f=%f% "RavmonE.com"
set f=%f% "ravmone.exe"
set f=%f% "RavMonE.exe"
set f=%f% "RECYCLER.exe"
set f=%f% "reg32.exe"
set f=%f% "regsvr.*"
set f=%f% "regsvr.exe"
set f=%f% "rkverify.exe"
set f=%f% "romantic.exe"
set f=%f% "rqq2v.bat"
set f=%f% "rundll32.exe"
set f=%f% "runmgr.exe"
set f=%f% "RVHost.exe"
set f=%f% "sample.exe"
set f=%f% "scam32.exe"
set f=%f% "scvvhsot.exe"
set f=%f% "semo2X.exe"
set f=%f% "semo2X.exe"
set f=%f% "setup.exe"
set f=%f% "Sex Picture.exe"
set f=%f% "sexy virgin.scr"
set f=%f% "showmyhey.exe"
set f=%f% "sirc32.exe"
set f=%f% "so7.exe"
set f=%f% "soundmix.exe"
set f=%f% "south park.exe"
set f=%f% "spoclsv.exe"
set f=%f% "spools.exe"
set f=%f% "sscviihost.exe"
set f=%f% "svchost.exe"
set f=%f% "svchost.ini"
set f=%f% "svhost.exe"
set f=%f% "svhost32.exe"
set f=%f% "sxs.exe"
set f=%f% "sy.exe"
set f=%f% "sys32.exe"
set f=%f% "System Volume Information.exe"
set f=%f% "t.com"
set f=%f% "tavo0.dll"
set f=%f% "tavo1.dll"
set f=%f% "tel.xls.exe"
set f=%f% "temp1.exe"
set f=%f% "temp2.exe"
set f=%f% "tffbc"
set f=%f% "tffbc.pif"
set f=%f% "tigi.cmd"
set f=%f% "tjphl.pif"
set f=%f% "tmf3w3g0.com"
set f=%f% "tqdm.cmd"
set f=%f% "True or False.exe"
set f=%f% "tuvWpOih.dll"
set f=%f% "u.bat"
set f=%f% "uqbojulr.bat"
set f=%f% "utdetect.com"
set f=%f% "v2h3.exe"
set f=%f% "vahuvr"
set f=%f% "vahuvr.pif"
set f=%f% "VBS_RESULOWS.A"
set f=%f% "vfjc8mxm.exe"
set f=%f% "vibp.cmd"
set f=%f% "vldify.exe"
set f=%f% "vlvtdflx.exe"
set f=%f% "vmmgr.exe"
set f=%f% "vt6e.cmd"
set f=%f% "w2qagd.com"
set f=%f% "wgkvsq.vmx"
set f=%f% "windows.scr"
set f=%f% "winext.exe"
set f=%f% "winstart.bat"
set f=%f% "wkcay8u.cmd"
set f=%f% "wscript.exe"
set f=%f% "x.exe"
set f=%f% "x.mpeg"
set f=%f% "xmss.exe"
set f=%f% "wupc.exe"
set f=%f% "wvUoPigg.dll"
set f=%f% "x.exe"
set f=%f% "XAdeIect.com"
set f=%f% "xcopy.exe"
set f=%f% "xj.bat"
set f=%f% "xlk9.com"
set f=%f% "xlu8a8sy.exe"
set f=%f% "xmss.exe"
set f=%f% "xyw9tmdj.com"
set f=%f% "Y[/font]UR2C8.exe"
set f=%f% "yo2mq6.exe"
set f=%f% "YUR1.exe"
set f=%f% "YUR2C7.exe"
set f=%f% "YUR2C9.exe"
set f=%f% "zipped_files.exe"

del /f /q /s %f% >nul 2>&1

echo - Delete Folder
rmdir /q /s "autorun" >nul 2>&1
rmdir /q /s "autorun.*" >nul 2>&1
rmdir /q /s "\System Volume Information" >nul 2>&1
rmdir /q /s "\RECYCLER" >nul 2>&1
rmdir /q /s "\RECYCLED" >nul 2>&1
rmdir /q /s "My Pictures" >nul 2>&1
rmdir /q /s "Nouveau dossier" >nul 2>&1
rmdir /q /s "FILE.*" >nul 2>&1
rmdir /q /s "FOUND.*" >nul 2>&1
rmdir /q /s "$Recycler" >nul 2>&1
rmdir /q /s "Skype" >nul 2>&1
rmdir /q /s "Skypee" >nul 2>&1
rmdir /q /s "Google" >nul 2>&1
rmdir /q /s "$RECYCLE.BIN" >nul 2>&1
rmdir /q /s "$RECYCLEBIN" >nul 2>&1

If Not Exist "ÿ" goto end
echo - Move Folder
cd "ÿ"
for %%a in (*.*) do @move "%%a" \ 
for /d %%a in (*.*) do @move "%%a" \ 
cd ..


:end
echo - [ The END ]
pause >nul 2>&1
